/** Curated emoji for Dot avatars: [emoji, search keywords]. */
export const EMOJI_DATA: ReadonlyArray<readonly [string, string]> = [
	["😀", "smile happy"],
	["😄", "happy grin"],
	["😊", "warm kind"],
	["😎", "cool"],
	["🤓", "nerd study"],
	["🧐", "curious detail"],
	["🤔", "think"],
	["😇", "angel"],
	["🥳", "party celebrate"],
	["🤩", "star wow"],
	["😴", "sleep rest"],
	["🤖", "robot ai"],
	["👻", "ghost"],
	["🦄", "unicorn magic"],
	["🐱", "cat pet"],
	["🐶", "dog pet"],
	["🦊", "fox clever"],
	["🐼", "panda"],
	["🦉", "owl wise night"],
	["🐝", "bee busy"],
	["🦋", "butterfly"],
	["🐙", "octopus"],
	["🐢", "turtle slow"],
	["🦁", "lion brave"],
	["🐳", "whale ocean"],
	["🐧", "penguin"],
	["🌱", "plant grow sprout"],
	["🌿", "herb leaf wellbeing"],
	["🌳", "tree nature"],
	["🌸", "flower blossom"],
	["🌻", "sunflower"],
	["🍀", "luck clover"],
	["🌵", "cactus"],
	["🍄", "mushroom"],
	["🌞", "sun day"],
	["🌙", "moon night"],
	["⭐", "star"],
	["✨", "sparkles magic"],
	["⚡", "lightning fast energy"],
	["🔥", "fire hot"],
	["💧", "water drop"],
	["🌊", "wave ocean"],
	["❄️", "snow cold"],
	["🌈", "rainbow"],
	["☁️", "cloud"],
	["🌍", "earth world globe"],
	["🪐", "planet space"],
	["🚀", "rocket launch"],
	["✈️", "plane travel"],
	["🚗", "car drive"],
	["🚲", "bike"],
	["🏠", "home house"],
	["🏢", "office building work"],
	["🏦", "bank money"],
	["🛒", "shop cart buy"],
	["📦", "package box delivery"],
	["📬", "mail inbox email"],
	["📧", "email mail"],
	["💬", "chat message talk"],
	["📞", "phone call"],
	["📅", "calendar schedule date"],
	["⏰", "alarm clock time reminder"],
	["⏳", "hourglass wait"],
	["📝", "note write memo"],
	["✍️", "writer write quill"],
	["📖", "book read"],
	["📚", "books library study"],
	["🔖", "bookmark"],
	["📰", "news paper"],
	["🗂️", "files folder archive"],
	["📁", "folder"],
	["📄", "document page"],
	["📊", "chart finance numbers"],
	["📈", "growth trend"],
	["📉", "decline"],
	["💰", "money cash"],
	["💳", "card payment"],
	["🧾", "receipt invoice"],
	["🧮", "abacus math calculator"],
	["🔢", "numbers"],
	["🔍", "search find"],
	["🔭", "telescope research scout"],
	["🔬", "microscope science"],
	["💡", "idea light"],
	["🧠", "brain mind"],
	["🎯", "target goal focus"],
	["🧭", "compass planner direction"],
	["🗺️", "map"],
	["📍", "pin location"],
	["🔔", "bell notify"],
	["🔒", "lock private"],
	["🔑", "key"],
	["🛡️", "shield safe"],
	["🛠️", "tools dev build"],
	["⚙️", "gear settings"],
	["🔧", "wrench fix"],
	["💻", "laptop computer code"],
	["⌨️", "keyboard"],
	["🖥️", "desktop"],
	["📱", "mobile phone"],
	["🎨", "art palette design"],
	["🖌️", "paint brush"],
	["🎬", "film movie"],
	["🎵", "music note"],
	["🎧", "headphones audio"],
	["🎮", "game"],
	["🎲", "dice random"],
	["🧩", "puzzle"],
	["🏆", "trophy win"],
	["🥇", "medal"],
	["⚽", "soccer sport"],
	["🏃", "run fitness"],
	["🧘", "yoga calm meditate"],
	["💪", "strong gym"],
	["🍎", "apple food health"],
	["☕", "coffee morning"],
	["🍳", "cook kitchen"],
	["🍕", "pizza"],
	["🍰", "cake"],
	["🎁", "gift"],
	["❤️", "love heart"],
	["💙", "blue heart"],
	["💚", "green heart"],
	["🧡", "orange heart"],
	["💜", "purple heart"],
	["🤝", "handshake deal"],
	["👋", "wave hello"],
	["👍", "thumbs up ok"],
	["🙌", "hooray"],
	["🧑‍💻", "developer coder"],
	["🧑‍🏫", "teacher"],
	["🧑‍⚕️", "doctor health"],
	["🧑‍🍳", "chef"],
	["🦸", "hero"],
	["🧙", "wizard"],
	["🎭", "theatre drama"],
	["🪄", "wand magic"],
	["🧪", "lab experiment"],
	["🩺", "stethoscope health"],
	["⚖️", "scales legal law"],
	["🏛️", "government"],
	["🎓", "graduation learn"],
	["🌐", "web internet"],
	["🔗", "link"],
	["📡", "antenna signal"],
	["🛰️", "satellite"],
	["🧰", "toolbox"],
];
