// Maps the curated Dot icon keys (src/shared/dot-icons.ts) to lucide components. The only place React meets the set.
import { DEFAULT_DOT_ICON, type DotIconKey, isDotIconKey } from "@shared/dot-icons";
import {
	Bell,
	BookOpen,
	Bot,
	Brain,
	Briefcase,
	Bug,
	Building2,
	Calendar,
	Camera,
	Car,
	ChartColumn,
	ClipboardList,
	Clock,
	Cloud,
	Code,
	Compass,
	CreditCard,
	Database,
	Dumbbell,
	FileText,
	Film,
	Folder,
	FolderKanban,
	Gift,
	GitBranch,
	Globe,
	GraduationCap,
	Handshake,
	Headphones,
	Heart,
	HeartPulse,
	House,
	Inbox,
	Landmark,
	Languages,
	Leaf,
	Lightbulb,
	ListChecks,
	Lock,
	type LucideIcon,
	Mail,
	MapPin,
	Megaphone,
	MessageCircle,
	Mic,
	Microscope,
	Monitor,
	Moon,
	Music,
	Newspaper,
	NotebookPen,
	Palette,
	PawPrint,
	PenLine,
	Phone,
	Plane,
	Plug,
	Receipt,
	Rocket,
	Scale,
	Search,
	Send,
	Shield,
	ShoppingBag,
	ShoppingCart,
	Sparkles,
	Sprout,
	Star,
	Sun,
	Tag,
	Target,
	Telescope,
	Terminal,
	TrendingUp,
	Truck,
	User,
	Users,
	Utensils,
	Wallet,
	Wrench,
	Zap,
} from "lucide-react";

export const DOT_ICON_COMPONENTS: Record<DotIconKey, LucideIcon> = {
	message: MessageCircle,
	sparkles: Sparkles,
	mail: Mail,
	inbox: Inbox,
	send: Send,
	calendar: Calendar,
	clock: Clock,
	search: Search,
	telescope: Telescope,
	microscope: Microscope,
	book: BookOpen,
	graduation: GraduationCap,
	newspaper: Newspaper,
	pen: PenLine,
	notebook: NotebookPen,
	wallet: Wallet,
	"credit-card": CreditCard,
	receipt: Receipt,
	landmark: Landmark,
	chart: ChartColumn,
	trending: TrendingUp,
	target: Target,
	plane: Plane,
	"map-pin": MapPin,
	compass: Compass,
	car: Car,
	truck: Truck,
	code: Code,
	terminal: Terminal,
	git: GitBranch,
	bug: Bug,
	wrench: Wrench,
	database: Database,
	cloud: Cloud,
	monitor: Monitor,
	plug: Plug,
	bot: Bot,
	shield: Shield,
	lock: Lock,
	scale: Scale,
	users: Users,
	user: User,
	handshake: Handshake,
	megaphone: Megaphone,
	briefcase: Briefcase,
	building: Building2,
	headphones: Headphones,
	phone: Phone,
	mic: Mic,
	file: FileText,
	folder: Folder,
	"folder-kanban": FolderKanban,
	"list-checks": ListChecks,
	clipboard: ClipboardList,
	home: House,
	heart: Heart,
	"heart-pulse": HeartPulse,
	leaf: Leaf,
	sprout: Sprout,
	dumbbell: Dumbbell,
	brain: Brain,
	lightbulb: Lightbulb,
	bell: Bell,
	globe: Globe,
	languages: Languages,
	"shopping-cart": ShoppingCart,
	"shopping-bag": ShoppingBag,
	gift: Gift,
	tag: Tag,
	utensils: Utensils,
	camera: Camera,
	film: Film,
	music: Music,
	palette: Palette,
	rocket: Rocket,
	zap: Zap,
	star: Star,
	moon: Moon,
	sun: Sun,
	paw: PawPrint,
};

/** The lucide component for a Dot icon key; unknown keys get the neutral default. */
export function dotIconComponent(key: string | undefined): LucideIcon {
	return DOT_ICON_COMPONENTS[isDotIconKey(key) ? key : DEFAULT_DOT_ICON];
}

export function DotIcon({
	name,
	size = 20,
	strokeWidth = 1.75,
	className,
}: {
	name: string | undefined;
	size?: number;
	strokeWidth?: number;
	className?: string;
}) {
	const Icon = dotIconComponent(name);
	return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" focusable="false" />;
}
