version: 2
updates:
  - package-ecosystem: npm
    directory: /desktop
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "app"]
    groups:
      app-minor-and-patch:
        update-types: ["minor", "patch"]
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: ["dependencies", "website"]
    groups:
      website-minor-and-patch:
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: ["dependencies", "ci"]
